import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Andika } from "next/font/google";


const andika = Andika({
  subsets: ["latin"],
  weight: ["400"], // Andika typically has regular weight
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <style>
      @import url(&#39;https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap&#39;); ;
      </style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${andika.className} antialiased`}
      >
        
        {children}
      </body>
    </html>
  );
}
